apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
  labels:
    app: sonar
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sonar

  template:
    metadata:
      labels:
        app: sonar

    spec:
      containers:
        - name: sonar
          image: sonarqube:community
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 9000
              protocol: TCP

          envFrom:
            - secretRef:
                name: sonar-secrets

          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data

            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions

            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs

      restartPolicy: Always

      volumes:
        - name: sonarqube-data
          emptyDir: {}

        - name: sonarqube-extensions
          emptyDir: {}

        - name: sonarqube-logs
          emptyDir: {}