apiVersion: v1
kind: Service
metadata:
  name: invoices-service
  labels:
    app: invoices

spec:
  type: ClusterIP

  selector:
    app: invoices

  ports:
    - name: http
      port: 5037
      targetPort: 8080